## Append samples you want in your CSV to this file as resources ##
resources:
- msvc_v1_mongodb.yaml
- crds_v1_mongodb.yaml
- msvc_v1_mysqldb.yaml
- msvc_v1_elasticsearch.yaml
- msvc_v1_helmmysqldb.yaml
- msvc_v1_helmelasticsearch.yaml
- msvc_v1_helmmongodb.yaml
- msvc_v1_helmredis.yaml
- msvc_v1_helmopensearch.yaml
- msvc_v1_helminfluxdb.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
