---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harborprojects/finalizers
  verbs:
  - update
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harborprojects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harboruseraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harboruseraccounts/finalizers
  verbs:
  - update
- apiGroups:
  - artifacts.kloudlite.io
  resources:
  - harboruseraccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - crds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - crds/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - crds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - edges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - edges/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - edges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - lambdas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - lambdas/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - lambdas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedresources/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedservices/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - managedservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.kloudlite.io
  resources:
  - routers/finalizers
  verbs:
  - update
- apiGroups:
  - crds.kloudlite.io
  resources:
  - routers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - csi.kloudlite.io
  resources:
  - drivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.kloudlite.io
  resources:
  - drivers/finalizers
  verbs:
  - update
- apiGroups:
  - csi.kloudlite.io
  resources:
  - drivers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearc.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearc.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearc.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearch.msvc.kloudlite.io
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.msvc.kloudlite.io
  resources:
  - kibanas/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.msvc.kloudlite.io
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - Clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - Clusters/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - Clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - edgeWatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - edgeWatchers/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.kloudlite.io
  resources:
  - edgeWatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - influxdb.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.external.kloudlite.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.external.kloudlite.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mongodb.external.kloudlite.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - clusterServices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - clusterServices/finalizers
  verbs:
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - clusterServices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - mongodb.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.external.kloudlite.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.external.kloudlite.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.external.kloudlite.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - clusterServices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - clusterServices/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - clusterServices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - standalone
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - standalone/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.msvc.kloudlite.io
  resources:
  - standalone/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - neo4j.msvc.kloudlite.io
  resources:
  - standaloneServices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neo4j.msvc.kloudlite.io
  resources:
  - standaloneServices/finalizers
  verbs:
  - update
- apiGroups:
  - neo4j.msvc.kloudlite.io
  resources:
  - standaloneServices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opensearch.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - aclaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - aclaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - aclaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - standaloneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - standaloneservices/finalizers
  verbs:
  - update
- apiGroups:
  - redis.msvc.kloudlite.io
  resources:
  - standaloneservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - aclusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - aclusers/finalizers
  verbs:
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - aclusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - admins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - admins/finalizers
  verbs:
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - admins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - topics/finalizers
  verbs:
  - update
- apiGroups:
  - redpanda.msvc.kloudlite.io
  resources:
  - topics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.aws.kloudlite.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.aws.kloudlite.io
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - s3.aws.kloudlite.io
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serverless.kloudlite.io
  resources:
  - lambdas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.kloudlite.io
  resources:
  - lambdas/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.kloudlite.io
  resources:
  - lambdas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - billingwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - billingwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - billingwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - statuswatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - statuswatchers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.kloudlite.io
  resources:
  - statuswatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - zookeeper.msvc.kloudlite.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zookeeper.msvc.kloudlite.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - zookeeper.msvc.kloudlite.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
