# Default values for kloudlite-autoscalers.
# This is a YAML-formatted file.
defaults:
  imageTag: "v1.0.5-nightly"
  imagePullPolicy: "Always"

serviceAccount:
  create: true
  nameSuffix: "sa"

clusterAutoscaler:
  enabled: true
  image:
    repository: "ghcr.io/kloudlite/cluster-autoscaler-amd64"
  nodeSelector: {}
  tolerations: []
