## Append samples you want in your CSV to this file as resources ##
resources:
- crds_v1_project.yaml
- crds_v1_router.yaml
- crds_v1_app.yaml
- crds_v1_managedservice.yaml
- crds_v1_managedresource.yaml
- crds_v1_pipeline.yaml
- crds_v1_mongodb.yaml
- mres_v1_mongodatabase.yaml
- msvc_v1_mongodb.yaml
- crds_v1_mongodbhelm.yaml
- mres.mongodbs.msvc_v1_database.yaml
- mongodbs.msvc_v1_database.yaml
- watchers.msvc_v1_mongodb.yaml
- crds_v1_account.yaml
- mongodb-standalone.msvc_v1_service.yaml
- mongodb-standalone.msvc_v1_database.yaml
- mongodb-cluster.msvc_v1_database.yaml
- mongodb-cluster.msvc_v1_service.yaml
- mysql-standalone.msvc_v1_service.yaml
- mysql-standalone.msvc_v1_database.yaml
- mysql-cluster.msvc_v1_service.yaml
- mysql-cluster.msvc_v1_database.yaml
- redis-standalone.msvc_v1_redis.yaml
- redis-cluster.msvc_v1_redis.yaml
- elasticsearch.msvc_v1_elasticsearch.yaml
- influxdb.msvc_v1_influxdb.yaml
- redis-standalone.msvc_v1_service.yaml
- redis-standalone.msvc_v1_keyprefix.yaml
- redis-cluster.msvc_v1_keyprefix.yaml
- redis-standalone.msvc_v1_aclaccount.yaml
- serverless_v1_lambda.yaml
- elasticsearch.msvc_v1_service.yaml
- opensearch.msvc_v1_service.yaml
- influxdb.msvc_v1_service.yaml
- influxdb.msvc_v1_bucket.yaml
- s3.aws_v1_bucket.yaml
- watcher_v1_statuswatcher.yaml
- watcher_v1_billingwatcher.yaml
- artifacts_v1_harborproject.yaml
- artifacts_v1_harboruseraccount.yaml
- redpanda.msvc_v1_service.yaml
- redpanda.msvc_v1_topic.yaml
- mongodb.external_v1_database.yaml
- mysql.external_v1_database.yaml
- crds_v1_accountrouter.yaml
- mongodb.msvc_v1_standaloneservice.yaml
- mongodb.msvc_v1_clusterservice.yaml
- mongodb.msvc_v1_database.yaml
- redis.msvc_v1_standaloneservice.yaml
- redis.msvc_v1_clusterservice.yaml
- redis.msvc_v1_aclaccount.yaml
- mysql.msvc_v1_standaloneservice.yaml
- mysql.msvc_v1_clusterservice.yaml
- mysql.msvc_v1_database.yaml
- redis.msvc_v1_aclconfigmap.yaml
- zookeeper.msvc_v1_service.yaml
- redpanda.msvc_v1_acluser.yaml
- extensions_v1_cluster.yaml
- redpanda.msvc_v1_admin.yaml
- neo4j.msvc_v1_standaloneservice.yaml
- artifacts_v1_harborwebhook.yaml
- csi_v1_awsebs.yaml
- csi_v1_driver.yaml
- csi_v1_storageclass.yaml
- crds_v1_edgerouter.yaml
- elasticsearch.msvc_v1_kibana.yaml
- extensions_v1_edgewatcher.yaml
- extensions_v1_edgeworker.yaml
- cluster-setup_v1_primarycluster.yaml
- cluster-setup_v1_secondarycluster.yaml
- crds_v1_env.yaml
- crds_v1_config.yaml
- crds_v1_secret.yaml
- crds_v1_secondaryenv.yaml
- crds_v1_anchor.yaml
- cluster-setup_v1_managedcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
