## Append samples you want in your CSV to this file as resources ##
resources:
- crds_v1_project.yaml
- crds_v1_router.yaml
- crds_v1_app.yaml
- crds_v1_managedservice.yaml
- crds_v1_managedresource.yaml
- crds_v1_pipeline.yaml
- crds_v1_mongodb.yaml
- mres_v1_mongodatabase.yaml
- msvc_v1_mongodb.yaml
- crds_v1_mongodbhelm.yaml
- mres.mongodbs.msvc_v1_database.yaml
- mongodbs.msvc_v1_database.yaml
- watchers.msvc_v1_mongodb.yaml
- crds_v1_account.yaml
- mongodb-standalone.msvc_v1_service.yaml
- mongodb-standalone.msvc_v1_database.yaml
- mongodb-cluster.msvc_v1_database.yaml
- mongodb-cluster.msvc_v1_service.yaml
- mysql-standalone.msvc_v1_service.yaml
- mysql-standalone.msvc_v1_database.yaml
- mysql-cluster.msvc_v1_service.yaml
- mysql-cluster.msvc_v1_database.yaml
- redis-standalone.msvc_v1_redis.yaml
- redis-cluster.msvc_v1_redis.yaml
- elasticsearch.msvc_v1_elasticsearch.yaml
- influxdb.msvc_v1_influxdb.yaml
- redis-standalone.msvc_v1_service.yaml
- redis-standalone.msvc_v1_keyprefix.yaml
- redis-cluster.msvc_v1_keyprefix.yaml
- redis-standalone.msvc_v1_aclaccount.yaml
- serverless_v1_lambda.yaml
- elasticsearch.msvc_v1_service.yaml
- opensearch.msvc_v1_service.yaml
- influxdb.msvc_v1_service.yaml
- influxdb.msvc_v1_bucket.yaml
- s3.aws_v1_bucket.yaml
- watcher_v1_statuswatcher.yaml
- watcher_v1_billingwatcher.yaml
- artifacts_v1_harborproject.yaml
- artifacts_v1_harboruseraccount.yaml
- redpanda.msvc_v1_service.yaml
- redpanda.msvc_v1_topic.yaml
- mongodb.external_v1_database.yaml
- mysql.external_v1_database.yaml
- crds_v1_accountrouter.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
