---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: externalapps.crds.kloudlite.io
spec:
  group: crds.kloudlite.io
  names:
    kind: ExternalApp
    listKind: ExternalAppList
    plural: externalapps
    singular: externalapp
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.lastReconcileTime
      name: Last_Reconciled_At
      type: date
    - jsonPath: .metadata.annotations.kloudlite\.io\/operator\.checks
      name: Checks
      type: string
    - jsonPath: .metadata.annotations.kloudlite\.io\/operator\.resource\.ready
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: ExternalApp is the Schema for the externalapps API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ExternalAppSpec defines the desired state of ExternalApp
            properties:
              intercept:
                properties:
                  deviceHostSuffix:
                    type: string
                  enabled:
                    type: boolean
                  portMappings:
                    items:
                      properties:
                        appPort:
                          type: integer
                        devicePort:
                          type: integer
                        protocol:
                          type: string
                      required:
                      - appPort
                      - devicePort
                      - protocol
                      type: object
                    type: array
                  toDevice:
                    type: string
                  toIPAddr:
                    type: string
                type: object
              record:
                type: string
              recordType:
                enum:
                - CNAME
                - IPAddr
                type: string
            required:
            - record
            - recordType
            type: object
          status: {}
        type: object
    served: true
    storage: true
    subresources:
      status: {}
